### ISSUE TITLE
I'd like to discuss this project.

### ISSUE THREAD

**Issue by kentaurse** [Better-HPC/keystone-api#440]

**Comment by djperrefort** [comment]
Hi @kentaurse,

Happy to chat. Email might be a better place to talk if you just want to have a general discussion. You're welcome to reach out at BetterHPC@gmail.com. Otherwise, I'm happy to have a conversation here if you have a technical question.

**Comment by kentaurse** [comment]
good.
I m web fulll stack developer and AI developer.

**Comment by djperrefort** [comment]
Sounds fun. Unfortunately, I'm still not clear on what it is you're hoping to discuss. Do you have a technical issue to raise? Or a general question?

**Comment by kentaurse** [comment]
I want to know about your org.

**Comment by djperrefort** [comment]
Better HPC is a software company for HPC related services and utilities. Is there something specific you're interested in? I'm still not clear on what your goal is, so if not I'm going to close this issue.

**Comment by kentaurse** [comment]
I am eager to bring my extensive experience and diverse skill set to your team and help drive innovative solutions.

**Comment by djperrefort** [comment]
Thanks for clarifying. Unfortunately, we don't currently have any open source initiatives nor are we currently looking to hire new team members. I have several ideas for open source projects down the line, but those won't be getting off the ground any time soon. Best of luck looking for new projects.

**Comment by kentaurse** [comment]
If you need developer, plz contact me
